## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
remote: origin
target-branch: master
chart-dirs:
- charts
validate-chart-schema: true
validate-maintainers: false
validate-yaml: true
exclude-deprecated: true
excluded-charts: []
check-version-increment: false
helm-extra-args: >-
  --set admiral.config.database.host=test-db
  --set admiral.config.database.user=test-user
  --set admiral.config.database.password=test-password
  --set admiral.config.auth.oidcIssuer=https://test-issuer.example.com
  --set admiral.config.auth.oidcClientId=test-client-id
  --set admiral.config.auth.oidcClientSecret=test-client-secret
  --set admiral.config.auth.sessionSecret=test-session-secret
  --set admiral.config.storage.manifestsBucket=test-manifests
  --set admiral.config.storage.revisionsBucket=test-revisions
  --set admiral.config.temporal.hostPort=temporal:7233
