remote: origin
target-branch: master
chart-dirs:
  - charts
excluded-charts: []
check-version-increment: false
validate-chart-schema: true
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
