# Trivy configuration file
timeout: 10m
skip-dirs:
  - "charts/*/ci"
  - ".github"

# Skip Helm chart directories for repository scan since they require values
skip-files:
  - "charts/*/values.yaml"
  - "charts/*/Chart.yaml"