{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "admiral-worker.fullname" . }}
  namespace: {{ include "admiral-worker.namespace" . }}
  labels:
    {{- include "admiral-worker.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  podSelector:
    matchLabels:
      {{- include "admiral-worker.selectorLabels" . | nindent 6 }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    # Allow ingress from pods with specific selector
    {{- if or .Values.networkPolicy.ingress.namespaceSelector .Values.networkPolicy.ingress.podSelector }}
    - from:
        {{- with .Values.networkPolicy.ingress.namespaceSelector }}
        - namespaceSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
        {{- with .Values.networkPolicy.ingress.podSelector }}
        - podSelector:
            {{- toYaml . | nindent 12 }}
        {{- end }}
      {{- if .Values.metrics.enabled }}
      ports:
        - protocol: TCP
          port: {{ .Values.metrics.port }}
      {{- end }}
    {{- end }}
    # Allow custom ingress rules
    {{- with .Values.networkPolicy.ingress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  egress:
    # Allow egress to DNS
    - to: []
      ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
    # Allow egress to Temporal server
    - to: []
      ports:
        - protocol: TCP
          port: 7233
    # Allow egress to Kubernetes API
    - to: []
      ports:
        - protocol: TCP
          port: 443
        - protocol: TCP
          port: 6443
    # Allow custom egress rules
    {{- with .Values.networkPolicy.egress.customRules }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}