{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "admiral-worker.fullname" . }}
  labels:
    {{- include "admiral-worker.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  {{- with .Values.rbac.rules }}
  {{- toYaml . | nindent 2 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "admiral-worker.fullname" . }}
  labels:
    {{- include "admiral-worker.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "admiral-worker.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "admiral-worker.serviceAccountName" . }}
    namespace: {{ include "admiral-worker.namespace" . }}
{{- end }}