apiVersion: v1
kind: Secret
metadata:
  name: {{ include "admiral-controller.fullname" . }}-secret
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "admiral-controller.labels" . | nindent 4 }}
type: Opaque
data:
  server-host-port: {{ .Values.admiral.config.server.hostPort | b64enc }}
  auth-token: {{ .Values.admiral.config.server.authToken | b64enc }}