apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "admiral-server.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "admiral-server.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.admiral.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "admiral-server.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        checksum/secret: {{ include (print $.Template.BasePath "/secret.yaml") . | sha256sum }}
        org.opencontainers.image.source: {{ .Values.admiral.image.repository }}
        {{- with .Values.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      labels:
        {{- include "admiral-server.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.admiral.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "admiral-server.serviceAccountName" . }}
      automountServiceAccountToken: false
      {{- with .Values.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- with .Values.initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.admiral.image.repository }}:{{ .Values.admiral.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.admiral.image.pullPolicy }}
          {{- if .Values.admiral.image.pullPolicy | default "IfNotPresent" | ne "Always" }}
          # Warning: imagePullPolicy is not set to Always, which is recommended for production
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.admiral.config.server.port }}
              protocol: TCP
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.livenessProbe.successThreshold }}
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
            successThreshold: {{ .Values.readinessProbe.successThreshold }}
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
          {{- end }}
          {{- if .Values.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: http
            initialDelaySeconds: {{ .Values.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            timeoutSeconds: {{ .Values.startupProbe.timeoutSeconds }}
            successThreshold: {{ .Values.startupProbe.successThreshold }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          env:
            - name: ADMIRAL_DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "admiral-server.fullname" . }}-secret
                  key: database-url
            - name: ADMIRAL_OIDC_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "admiral-server.fullname" . }}-secret
                  key: oidc-client-secret
            - name: ADMIRAL_SESSION_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ include "admiral-server.fullname" . }}-secret
                  key: session-secret
            - name: ADMIRAL_STORAGE_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "admiral-server.fullname" . }}-secret
                  key: storage-access-key
            - name: ADMIRAL_STORAGE_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "admiral-server.fullname" . }}-secret
                  key: storage-secret-key
            {{- with .Values.extraEnvVars }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          volumeMounts:
            - name: config
              mountPath: /app/config.yaml
              subPath: config.yaml
              readOnly: true
            - name: tmp
              mountPath: /tmp
            {{- with .Values.extraVolumeMounts }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          resources:
            {{- toYaml .Values.admiral.resources | nindent 12 }}
        {{- with .Values.sidecars }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      volumes:
        - name: config
          configMap:
            name: {{ include "admiral-server.fullname" . }}-config
        - name: tmp
          emptyDir: {}
        {{- with .Values.extraVolumes }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.admiral.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.admiral.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- else }}
      {{- if .Values.affinity.podAntiAffinity.enabled }}
      affinity:
        podAntiAffinity:
          {{- if eq .Values.affinity.podAntiAffinity.type "hard" }}
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  {{- include "admiral-server.selectorLabels" . | nindent 18 }}
              topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
          {{- else }}
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchLabels:
                    {{- include "admiral-server.selectorLabels" . | nindent 20 }}
                topologyKey: {{ .Values.affinity.podAntiAffinity.topologyKey }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- with .Values.admiral.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}