apiVersion: v1
kind: Pod
metadata:
  name: insecure-pod
spec:
  containers:
  - name: bad-container
    image: nginx
    securityContext:
      privileged: true
      runAsUser: 0
    env:
    - name: PASSWORD
      value: "hardcoded-password-123"
    - name: API_KEY
      value: "sk-1234567890abcdef"