name: Security Scan

on:
  pull_request:
    paths:
      - "charts/**"
      - ".github/workflows/security-scan.yaml"
  push:
    branches:
      - master
    paths:
      - "charts/**"

permissions:
  contents: read
  security-events: write

jobs:
  checkov-scan:
    name: Checkov Security Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Run Checkov against charts (excluding Helm templates)
        id: checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: charts/
          framework: kubernetes
          output_format: sarif
          output_file_path: checkov-results.sarif
          soft_fail: true
          skip_path: charts/*/templates,charts/*/ci

      - name: Upload SARIF results
        if: always()
        uses: github/codeql-action/upload-sarif@4e828ff8d448a8a6e532957b1811f387a63867e8 # v3.29.4
        with:
          sarif_file: checkov-results.sarif
          category: checkov-kubernetes

  kubesec-scan:
    name: Kubesec Security Scan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        chart:
          - admiral-server
          - admiral-controller
          - admiral-worker
    steps:
      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Helm
        uses: azure/setup-helm@b9e51907a09c216f16ebe8536097933489208112 # v4.3.0

      - name: Template Helm chart
        run: |
          helm template ${{ matrix.chart }} ./charts/${{ matrix.chart }} > ${{ matrix.chart }}-rendered.yaml

      - name: Run Kubesec scan
        uses: controlplaneio/kubesec-action@v0.0.2
        with:
          input: ${{ matrix.chart }}-rendered.yaml

